---
# Source: worker/templates/skyramp-worker-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skyramp-worker-worker
  labels:
    helm.sh/chart: worker-0.1.85
    app.kubernetes.io/name: skyramp-worker
    app.kubernetes.io/instance: my-worker
    app.kubernetes.io/part-of: skyramp
    app.kubernetes.io/version: "v0.4.94"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups: [""]
  resources: ["nodes/proxy"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]

