---
# Source: worker/templates/skyramp-worker-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: skyramp-worker
  labels:
    helm.sh/chart: worker-0.1.86
    app.kubernetes.io/name: skyramp-worker
    app.kubernetes.io/instance: dev
    app.kubernetes.io/part-of: skyramp
    app.kubernetes.io/version: "v0.4.95"
    app.kubernetes.io/managed-by: Helm
data:
  management-plane-config.yaml: |
    mongoConfig:
      database: dashboarddb
      enabled: true
      mockCollection: servicemocks
      mongodbUrl: mongodb://admin:pa$$word@mongo-datastore-svc.skyramp:27017/?authSource=admin&authMechanism=SCRAM-SHA-256
      testResultCollection: testresults
    metricsConfig:
      type: opentsdb
      enabled: true
      pushGatewayUrl: http://opentsdb.skyramp:9091
  config.yaml: |
    backend: kubernetes
    managementPort: 35142
  resources.yaml: "" 
  target-config.yaml: ""
immutable: false