---
# Source: worker/templates/skyramp-worker-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skyramp-worker
  labels:
    helm.sh/chart: worker-0.1.86
    app.kubernetes.io/name: skyramp-worker
    app.kubernetes.io/instance: dev
    app.kubernetes.io/part-of: skyramp
    app.kubernetes.io/version: "v0.4.95"
    app.kubernetes.io/managed-by: Helm